repos:
  - repo: 'https://github.com/jorisroovers/gitlint'
    rev: v0.19.1
    hooks:
    - id: gitlint
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-builtin-literals
      - id: detect-private-key
      - id: mixed-line-ending
      - id: check-merge-conflict
  - repo: 'https://github.com/charliermarsh/ruff-pre-commit'
    rev: v0.0.278
    hooks:
      - id: ruff
        args:
          - --fix
          - --ignore
          - E501  # Ignore line length errors
  - repo: 'https://github.com/pycqa/isort'
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: 'https://github.com/psf/black'
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3
ci:
  autofix_commit_msg: 🎨 [pre-commit.ci] Auto format from pre-commit.com hooks
  autoupdate_commit_msg: ⬆ [pre-commit.ci] pre-commit autoupdate
